### ISSUE TITLE
Support for WPA 2 Enterprise 

### ISSUE THREAD

**Issue by jeffreytgilbert** [tessel/rf-nrf24#14]
I know this is an issue with the baseband chip on the tessel itself, but I saw tessel was coming out with a new iteration, so hopefully this serves as a reminder that the lack of WPA2 enterprise functionality is a real back breaker for getting this thing going at work.

**Comment by kevinmehall** [comment]
This repository is actually for the driver for our [low-power radio module](https://tessel.io/modules#module-nRF24), not wifi. The more appropriate place for this kind of feedback would be [the forum](https://forums.tessel.io/) in the future. You can log in via GitHub.

But to answer your question, the new hardware is capable of WPA2 Enterprise. I can't guarantee it will have first-class software support to set it up with `tessel wifi` by launch time, but in that case it will be possible with a little manual configuration.
